components/modal-add-location.js
https://github.com/ritoplz/ritoplz/issues/75
=> Fix select state on add/edit location

components/modal-add-summoner.js, components/my-summoners.js, containers/profile-content.js
https://github.com/ritoplz/ritoplz/issues/84
=> Fix tutorial modal

actions/fetch-rankings.js, components/ranking-user.js
https://github.com/ritoplz/ritoplz/issues/94
=> Add summoner hot streak

components/meta.js, static/drift.js
https://github.com/ritoplz/ritoplz/issues/73
=> Add Drift integration

actions/add-summoner.js, actions/confirm-summoner.js, actions/edit-user.js, actions/fetch-account.js, actions/fetch-rankings.js, actions/login.js, actions/signup.js, components/modal-add-location.js, components/modal-add-summoner.js, containers/profile-content.js, services/api.js
https://github.com/ritoplz/ritoplz/issues/103
=> Add interceptors

components/unranked-user.js, containers/rankings-list.js
https://github.com/ritoplz/ritoplz/issues/93
=> Add unranked rankings

containers/onboard.js, package.json, pages/welcome.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/157
=> Copy to clipboard

components/my-summoners.js, components/summoner.js, containers/form-signup.js, containers/onboard.js, containers/profile-content.js, pages/index.js
https://github.com/ritoplz/ritoplz/issues/156
=> Disable buttons on request

components/ranking-user.js, components/top-player.js, components/unranked-user.js
https://github.com/ritoplz/ritoplz/issues/208
=> Fix summoner avatar

components/ui/index.js, components/ui/theme.js, components/ui/ui-button.js, pages/ui.js
https://github.com/ritoplz/ritoplz/issues/214
=> Add ui-button

components/ui/index.js, components/ui/text-input.js, components/ui/theme.js, pages/ui.js
https://github.com/ritoplz/ritoplz/issues/211
=> Add text-input

components/ranking-user.js, components/ui/theme.js, components/ui/ui-button.js, package.json, yarn.lock
https://github.com/ritoplz/ritoplz/issues/231
=> Add ranking-user

pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/230
=> Add rankings page

components/ui/ui-button.js
https://github.com/ritoplz/ritoplz/issues/226
=> Add ui-button block

package.json, pages/login.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/244
=> Add goot :heart:

pages/settings.js
https://github.com/ritoplz/ritoplz/issues/247
=> Add page-title on Settings

components/ui/text-input.js, components/ui/ui-select.js, pages/settings.js
https://github.com/ritoplz/ritoplz/issues/246
=> Add ui-select on Settings

components/ui/form-control.js
https://github.com/ritoplz/ritoplz/issues/248
=> Fix cancel button on Settings

actions/add-summoner.js, actions/confirm-summoner.js, actions/edit-user.js, actions/fetch-account.js, actions/fetch-rankings.js, actions/login.js, actions/signup.js, components/ui/text-input.js, layouts/page.js, package.json, pages/login.js, services/api.js, store/configure-store.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/255
=> Add login functionality

components/register-sidebar.js, pages/login.js, pages/signup.js
https://github.com/ritoplz/ritoplz/issues/266
=> Add register-sidebar

pages/signup.js
https://github.com/ritoplz/ritoplz/issues/256
=> Add signup functionality

components/register-main.js, pages/login.js, pages/signup.js
https://github.com/ritoplz/ritoplz/issues/267
=> Add register-main

actions/login.js, package.json, pages/login.js, reducers/login.js, services/api.js, services/auth.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/264
=> Add token cookies on Login

services/auth.js
https://github.com/ritoplz/ritoplz/issues/273
=> Add expire date to cookie

actions/signup.js, pages/signup.js, reducers/signup.js
https://github.com/ritoplz/ritoplz/issues/272
=> Add signup process

actions/fetch-account.js, components/ui/text-input.js, pages/settings.js, services/api.js
https://github.com/ritoplz/ritoplz/issues/253
=> Add fetch user on Settings

actions/edit-user.js, components/ui/form-control.js, pages/settings.js, reducers/edit-user.js
https://github.com/ritoplz/ritoplz/issues/254
=> Add settings

components/ui/text-input.js
https://github.com/ritoplz/ritoplz/issues/293
=> Fix input-text onChange

components/legal-heading.js, components/legal-text.js, components/legal-title.js, components/ui/theme.js, pages/privacy.js
https://github.com/ritoplz/ritoplz/issues/291
=> Add Privacy Policy

components/register-footer.js, pages/terms.js
https://github.com/ritoplz/ritoplz/issues/290
=> Add Terms of Services

components/menu.js
https://github.com/ritoplz/ritoplz/issues/298
=> Add login button on header when user is not logged

components/menu-user.js, components/ui/form-control.js, pages/login.js, pages/signup.js
https://github.com/ritoplz/ritoplz/issues/287
https://github.com/ritoplz/ritoplz/issues/286
https://github.com/ritoplz/ritoplz/issues/285
=> Fix redirects to profile

components/ranking-user.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/301
https://github.com/ritoplz/ritoplz/issues/302
=> Add fetch rankings

actions/fetch-rankings.js, components/ranking-user.js, package.json, pages/rankings.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/92
=> Add infinite loading

package.json, yarn.lock
https://github.com/ritoplz/ritoplz/issues/311
=> Update to react-infinite-scroller v1.0.10

env-config.js, package.json, services/api.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/265
=> Add env vars

pages/login.js, pages/reset-password.js
https://github.com/ritoplz/ritoplz/issues/288
=> Add reset-password page

pages/sudo-mode.js
https://github.com/ritoplz/ritoplz/issues/315
=> Add sudo-mode page

components/ui/social-button.js, pages/settings.js
https://github.com/ritoplz/ritoplz/issues/320
=> Fix social button icon

components/ranking-heading.js, components/ui/theme.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/307
=> Add ranking heading

components/icons/index.js, components/icons/spinner-icon.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/305
=> Add spinner icon

components/menu.js
https://github.com/ritoplz/ritoplz/issues/324
=> Fix client/server rendering of menu

components/ranking-heading.js, components/ranking-user.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/308
=> Add different style if its users summoner

pages/profile.js
https://github.com/ritoplz/ritoplz/issues/250
=> Add profile page

components/register-footer.js, pages/faq.js, pages/privacy.js, pages/terms.js
https://github.com/ritoplz/ritoplz/issues/292
=> Add FAQ page

components/ui/ui-select.js, pages/profile.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/306
=> Add filter

components/ui/ui-select.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/333
=> Filter rankings

package.json, pages/settings.js
https://github.com/ritoplz/ritoplz/issues/281
=> Add save location

components/profile-title.js, components/summoner-active.js, components/summoner-inactive.js, components/summoner-list.js, components/summoner.js, components/ui/theme.js, components/ui/ui-button.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/336
=> Add fetch summoners on profile

actions/add-summoner.js, components/ui/ui-link.js, pages/add-summoner.js
https://github.com/ritoplz/ritoplz/issues/338
=> Add add-summoner page

pages/reset-password.js
https://github.com/ritoplz/ritoplz/issues/352
=> Redirect to login if user is not logged on reset-password

pages/profile.js
https://github.com/ritoplz/ritoplz/issues/350
=> Redirect to login if user is not logged on profile

components/profile-title.js
https://github.com/ritoplz/ritoplz/issues/348
=> Fix location styles

components/icons/spinner-icon.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/347
=> Fix spinner on Profile

pages/logout.js
https://github.com/ritoplz/ritoplz/issues/359
=> Add logout

components/empty-state.js, components/summoner-list.js
https://github.com/ritoplz/ritoplz/issues/342
=> Add empty-state

components/summoner-inactive.js, components/summoner-list.js, components/summoner.js, components/ui/ui-button.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/337
=> Add confirm summoner functionality

pages/faq.js, pages/how-to.js
https://github.com/ritoplz/ritoplz/issues/346
=> Add how-to page

components/profile-title.js, components/summoner-active.js, components/summoner-inactive.js, components/summoner-list.js, components/summoner.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/339
=> Add summoner not confirmed ui

components/ranking-heading.js
https://github.com/ritoplz/ritoplz/issues/365
=> Fix ranking position

components/menu.js, components/page-title.js, pages/my-summoners.js, pages/profile.js, pages/settings.js
https://github.com/ritoplz/ritoplz/issues/396
=> Add my summoners page

components/latest-matches.js, components/stats.js, components/summoners.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/341
https://github.com/ritoplz/ritoplz/issues/138
=> Add profile stats

components/summoners-active.js, components/summoners-inactive.js, components/summoners.js, pages/my-summoners.js, pages/profile.js
https://github.com/ritoplz/ritoplz/issues/401
https://github.com/ritoplz/ritoplz/issues/402
https://github.com/ritoplz/ritoplz/issues/403
=> Add empty state

components/ranking-heading.js, pages/rankings.js
https://github.com/ritoplz/ritoplz/issues/404
=> Fix rankings

package.json, pages/login.js, pages/signup.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/421
=> Fix login/signup Cannot read property format of undefined

components/menu.js, pages/login.js, pages/signup.js
https://github.com/ritoplz/ritoplz/issues/423
=> Fix menu — remove settings if user is not logged

pages/how-to.js
https://github.com/ritoplz/ritoplz/issues/424
=> Fix how-to — it shouldnt be an authenticated page

pages/faq.js
https://github.com/ritoplz/ritoplz/issues/431
=> Fix typo FAQ

components/home-analytics.js
https://github.com/ritoplz/ritoplz/issues/430
=> Fix typo Landing page

package.json, pages/player.js, server.js, services/api.js, services/routes.js, yarn.lock
https://github.com/ritoplz/ritoplz/issues/437
=> Add prettier url

__tests__/components/__snapshots__/form-control.js.snap, __tests__/components/form-control.js, components/ui/form-control.js, components/ui/ui-link.js, next.config.js, package.json
https://github.com/ritoplz/ritoplz/issues/413
=> Add form-control test

__tests__/components/__snapshots__/form-control.js.snap, __tests__/components/__snapshots__/ui-link.js.snap, __tests__/components/form-control.js, __tests__/components/ui-link.js
https://github.com/ritoplz/ritoplz/issues/414
=> Add ui-link test

__tests__/components/__snapshots__/fieldset.js.snap, __tests__/components/fieldset.js
https://github.com/ritoplz/ritoplz/issues/412
=> Add fieldset test

package.json
https://github.com/ritoplz/ritoplz/issues/443
=> Add now alias

pages/settings.js
https://github.com/ritoplz/ritoplz/issues/448
=> Add coming soon

components/ranking-user.js, components/summoners.js
https://github.com/ritoplz/ritoplz/issues/455
=> Fix ranking summoner name

components/profile-summoners.js, components/ranking-user.js
https://github.com/ritoplz/ritoplz/issues/463
=> Update summoner icon

components/profile-summoner.js
https://github.com/ritoplz/ritoplz/issues/469
=> Fix profile unranked

components/profile-match.js
https://github.com/ritoplz/ritoplz/issues/472
=> Fix match default values
